query FetchTransactions {
    transactions {
        id
        products {
            id
            name
            description
            barcode
            price
        }
        createdAt
        updatedAt
    }
}
