mutation AddProduct ($name: String!, $description: String, $barcode: String, $price: Float!) {
    addProduct(name: $name, description: $description, barcode: $barcode, price: $price)
    {
        name
        description
        barcode
        price
    }
}